// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package db

import (
	"context"
)

const getCalendarCache = `-- name: GetCalendarCache :one
SELECT data, scraped_at
FROM calendar_cache
WHERE calendar_type = ?
LIMIT 1
`

type GetCalendarCacheRow struct {
	Data      string
	ScrapedAt string
}

func (q *Queries) GetCalendarCache(ctx context.Context, calendarType string) (GetCalendarCacheRow, error) {
	row := q.db.QueryRowContext(ctx, getCalendarCache, calendarType)
	var i GetCalendarCacheRow
	err := row.Scan(&i.Data, &i.ScrapedAt)
	return i, err
}

const upsertCalendarCache = `-- name: UpsertCalendarCache :exec
INSERT INTO calendar_cache (calendar_type, data)
VALUES (?, ?)
ON CONFLICT(calendar_type) DO UPDATE
SET
  data = EXCLUDED.data,
  scraped_at = CURRENT_TIMESTAMP
`

type UpsertCalendarCacheParams struct {
	CalendarType string
	Data         string
}

func (q *Queries) UpsertCalendarCache(ctx context.Context, arg UpsertCalendarCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertCalendarCache, arg.CalendarType, arg.Data)
	return err
}
