// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notice.sql

package db

import (
	"context"
	"database/sql"
)

const clearNotices = `-- name: ClearNotices :exec
DELETE FROM notices
`

func (q *Queries) ClearNotices(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearNotices)
	return err
}

const countNotices = `-- name: CountNotices :one
SELECT
  COUNT(1)
FROM
  notices
`

func (q *Queries) CountNotices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLatestNoticeInfo = `-- name: GetLatestNoticeInfo :one
SELECT
  CAST(COALESCE(MAX(posted_date), '') AS TEXT) AS posted_date,
  CAST(COALESCE(MAX(source_order), 0) AS INTEGER) AS source_order
FROM
  notices
`

type GetLatestNoticeInfoRow struct {
	PostedDate  string
	SourceOrder int64
}

func (q *Queries) GetLatestNoticeInfo(ctx context.Context) (GetLatestNoticeInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestNoticeInfo)
	var i GetLatestNoticeInfoRow
	err := row.Scan(&i.PostedDate, &i.SourceOrder)
	return i, err
}

const getNoticeAttachments = `-- name: GetNoticeAttachments :many
SELECT
  id, notice_id, label, url, local_path, created_at
FROM
  notice_attachments
WHERE
  notice_id = ?
`

func (q *Queries) GetNoticeAttachments(ctx context.Context, noticeID string) ([]NoticeAttachment, error) {
	rows, err := q.db.QueryContext(ctx, getNoticeAttachments, noticeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NoticeAttachment{}
	for rows.Next() {
		var i NoticeAttachment
		if err := rows.Scan(
			&i.ID,
			&i.NoticeID,
			&i.Label,
			&i.Url,
			&i.LocalPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNoticeWithState = `-- name: GetNoticeWithState :one
SELECT
  n.id, n.title, n.summary, n.full_title, n.content, n.posted_date, n.category, n.is_cached, n.is_urgent, n.source_order, n.created_at, n.updated_at,
  COALESCE(s.is_pinned, 0) AS is_pinned,
  COALESCE(s.is_read, 0) AS is_read
FROM
  notices n
  LEFT JOIN user_states s ON n.id = s.notice_id
WHERE
  n.id = ?
LIMIT
  1
`

type GetNoticeWithStateRow struct {
	ID          string
	Title       string
	Summary     sql.NullString
	FullTitle   sql.NullString
	Content     sql.NullString
	PostedDate  string
	Category    string
	IsCached    int64
	IsUrgent    int64
	SourceOrder int64
	CreatedAt   string
	UpdatedAt   string
	IsPinned    int64
	IsRead      int64
}

func (q *Queries) GetNoticeWithState(ctx context.Context, id string) (GetNoticeWithStateRow, error) {
	row := q.db.QueryRowContext(ctx, getNoticeWithState, id)
	var i GetNoticeWithStateRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.FullTitle,
		&i.Content,
		&i.PostedDate,
		&i.Category,
		&i.IsCached,
		&i.IsUrgent,
		&i.SourceOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPinned,
		&i.IsRead,
	)
	return i, err
}

const insertNotice = `-- name: InsertNotice :execrows
INSERT INTO
  notices (id, title, summary, posted_date, category, is_urgent, source_order)
VALUES
  (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type InsertNoticeParams struct {
	ID          string
	Title       string
	Summary     sql.NullString
	PostedDate  string
	Category    string
	IsUrgent    int64
	SourceOrder int64
}

func (q *Queries) InsertNotice(ctx context.Context, arg InsertNoticeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertNotice,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.PostedDate,
		arg.Category,
		arg.IsUrgent,
		arg.SourceOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listNoticesWithState = `-- name: ListNoticesWithState :many
SELECT
  n.id, n.title, n.summary, n.full_title, n.content, n.posted_date, n.category, n.is_cached, n.is_urgent, n.source_order,
  COALESCE(s.is_pinned, 0) AS is_pinned,
  COALESCE(s.is_read, 0) AS is_read
FROM
  notices n
  LEFT JOIN user_states s ON n.id = s.notice_id
WHERE
  (
    CAST(?1 AS TEXT) IS NULL
    OR n.category = ?1
  )
  AND (
    CAST(?2 AS BOOL) IS NULL
    OR n.is_urgent = ?2
  )
  AND (
    CAST(?3 AS BOOL) IS NULL
    OR COALESCE(s.is_pinned, 0) = ?3
  )
  AND (
    CAST(?4 AS BOOL) IS NULL
    OR COALESCE(s.is_read, 0) != ?4
  )
ORDER BY
  n.posted_date DESC,
  n.source_order DESC
`

type ListNoticesWithStateParams struct {
	Category sql.NullString
	Urgent   sql.NullBool
	Pinned   sql.NullBool
	Unread   sql.NullBool
}

type ListNoticesWithStateRow struct {
	ID          string
	Title       string
	Summary     sql.NullString
	FullTitle   sql.NullString
	Content     sql.NullString
	PostedDate  string
	Category    string
	IsCached    int64
	IsUrgent    int64
	SourceOrder int64
	IsPinned    int64
	IsRead      int64
}

func (q *Queries) ListNoticesWithState(ctx context.Context, arg ListNoticesWithStateParams) ([]ListNoticesWithStateRow, error) {
	rows, err := q.db.QueryContext(ctx, listNoticesWithState,
		arg.Category,
		arg.Urgent,
		arg.Pinned,
		arg.Unread,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNoticesWithStateRow{}
	for rows.Next() {
		var i ListNoticesWithStateRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.FullTitle,
			&i.Content,
			&i.PostedDate,
			&i.Category,
			&i.IsCached,
			&i.IsUrgent,
			&i.SourceOrder,
			&i.IsPinned,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPinState = `-- name: SetPinState :exec
INSERT INTO
  user_states (notice_id, is_pinned, pinned_at)
VALUES
  (
    ?,
    ?,
    CASE
      WHEN ? = 1 THEN CURRENT_TIMESTAMP
      ELSE NULL
    END
  )
ON CONFLICT(notice_id) DO UPDATE
SET
  is_pinned = EXCLUDED.is_pinned,
  pinned_at = EXCLUDED.pinned_at
`

type SetPinStateParams struct {
	NoticeID string
	IsPinned int64
}

func (q *Queries) SetPinState(ctx context.Context, arg SetPinStateParams) error {
	_, err := q.db.ExecContext(ctx, setPinState, arg.NoticeID, arg.IsPinned, arg.IsPinned)
	return err
}

const setReadState = `-- name: SetReadState :exec
INSERT INTO
  user_states (notice_id, is_read, last_read_at)
VALUES
  (
    ?,
    ?,
    CASE
      WHEN ? = 1 THEN CURRENT_TIMESTAMP
      ELSE NULL
    END)
ON CONFLICT(notice_id) DO UPDATE
SET
  is_read = EXCLUDED.is_read,
  last_read_at = EXCLUDED.last_read_at
`

type SetReadStateParams struct {
	NoticeID string
	IsRead   int64
}

func (q *Queries) SetReadState(ctx context.Context, arg SetReadStateParams) error {
	_, err := q.db.ExecContext(ctx, setReadState, arg.NoticeID, arg.IsRead, arg.IsRead)
	return err
}

const updateNotice = `-- name: UpdateNotice :exec
UPDATE notices
SET
  title = ?1,
  summary = ?2,
  posted_date = ?3,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ?4
  AND (
    title != ?1
    OR summary != ?2
    OR posted_date != ?3
  )
`

type UpdateNoticeParams struct {
	Title      string
	Summary    sql.NullString
	PostedDate string
	ID         string
}

func (q *Queries) UpdateNotice(ctx context.Context, arg UpdateNoticeParams) error {
	_, err := q.db.ExecContext(ctx, updateNotice,
		arg.Title,
		arg.Summary,
		arg.PostedDate,
		arg.ID,
	)
	return err
}

const updateNoticeDetails = `-- name: UpdateNoticeDetails :exec
UPDATE notices
SET
  full_title = ?,
  content = ?,
  is_cached = 1,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ?
`

type UpdateNoticeDetailsParams struct {
	FullTitle sql.NullString
	Content   sql.NullString
	ID        string
}

func (q *Queries) UpdateNoticeDetails(ctx context.Context, arg UpdateNoticeDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateNoticeDetails, arg.FullTitle, arg.Content, arg.ID)
	return err
}

const upsertNotice = `-- name: UpsertNotice :exec
INSERT INTO
  notices (id, title, summary, posted_date, category, is_urgent, source_order)
VALUES
  (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE
  SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    posted_date = EXCLUDED.posted_date,
    category = EXCLUDED.category,
    is_urgent = EXCLUDED.is_urgent,
    source_order = EXCLUDED.source_order
  WHERE
    COALESCE(notices.title, '') != COALESCE(EXCLUDED.title, '')
`

type UpsertNoticeParams struct {
	ID          string
	Title       string
	Summary     sql.NullString
	PostedDate  string
	Category    string
	IsUrgent    int64
	SourceOrder int64
}

func (q *Queries) UpsertNotice(ctx context.Context, arg UpsertNoticeParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotice,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.PostedDate,
		arg.Category,
		arg.IsUrgent,
		arg.SourceOrder,
	)
	return err
}

const upsertNoticeAttachment = `-- name: UpsertNoticeAttachment :exec
INSERT INTO
  notice_attachments (id, notice_id, label, url)
VALUES
  (?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type UpsertNoticeAttachmentParams struct {
	ID       string
	NoticeID string
	Label    string
	Url      string
}

func (q *Queries) UpsertNoticeAttachment(ctx context.Context, arg UpsertNoticeAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertNoticeAttachment,
		arg.ID,
		arg.NoticeID,
		arg.Label,
		arg.Url,
	)
	return err
}
