// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddToUserRoutine(ctx context.Context, classID string) error
	ClearNotices(ctx context.Context) error
	ClearOfferedCourses(ctx context.Context) error
	CountNotices(ctx context.Context) (int64, error)
	GetLatestNoticeInfo(ctx context.Context) (GetLatestNoticeInfoRow, error)
	GetNoticeAttachments(ctx context.Context, noticeID string) ([]NoticeAttachment, error)
	GetNoticeWithState(ctx context.Context, id string) (GetNoticeWithStateRow, error)
	GetUserRoutine(ctx context.Context) ([]OfferedCourse, error)
	InsertNotice(ctx context.Context, arg InsertNoticeParams) (int64, error)
	InsertOfferedCourse(ctx context.Context, arg InsertOfferedCourseParams) error
	RemoveFromUserRoutine(ctx context.Context, classID string) error
	SearchNoticesWithState(ctx context.Context, arg SearchNoticesWithStateParams) ([]SearchNoticesWithStateRow, error)
	SearchOfferedCourses(ctx context.Context, search sql.NullString) ([]OfferedCourse, error)
	SetPinState(ctx context.Context, arg SetPinStateParams) error
	SetReadState(ctx context.Context, arg SetReadStateParams) error
	UpdateNotice(ctx context.Context, arg UpdateNoticeParams) error
	UpdateNoticeDetails(ctx context.Context, arg UpdateNoticeDetailsParams) error
	UpsertNotice(ctx context.Context, arg UpsertNoticeParams) error
	UpsertNoticeAttachment(ctx context.Context, arg UpsertNoticeAttachmentParams) error
}

var _ Querier = (*Queries)(nil)
