// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type CalendarCache struct {
	CalendarType string
	Data         string
	ScrapedAt    string
}

type Notice struct {
	ID          string
	Title       string
	Summary     sql.NullString
	FullTitle   sql.NullString
	Content     sql.NullString
	PostedDate  string
	Category    string
	IsCached    int64
	IsUrgent    int64
	SourceOrder int64
	CreatedAt   string
	UpdatedAt   string
}

type NoticeAttachment struct {
	ID        string
	NoticeID  string
	Label     string
	Url       string
	LocalPath sql.NullString
	CreatedAt string
}

type OfferedCourse struct {
	ClassID     string
	CourseCode  sql.NullString
	CourseTitle string
	Section     string
	Faculty     sql.NullString
	ClassType   sql.NullString
	Day         sql.NullString
	StartTime   sql.NullString
	EndTime     sql.NullString
	Room        sql.NullString
	Department  sql.NullString
}

type UserRoutine struct {
	ClassID string
	AddedAt string
}

type UserState struct {
	NoticeID   string
	IsPinned   int64
	IsRead     int64
	PinnedAt   sql.NullString
	LastReadAt sql.NullString
}
