// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type CalendarCache struct {
	CalendarType string
	Data         string
	ScrapedAt    time.Time
}

type ClassSchedule struct {
	ID        int64
	ClassID   string
	ClassType sql.NullString
	Day       sql.NullString
	StartTime sql.NullString
	EndTime   sql.NullString
	Room      sql.NullString
}

type Notice struct {
	ID          string
	Title       string
	Summary     sql.NullString
	FullTitle   sql.NullString
	Content     sql.NullString
	PostedDate  time.Time
	Category    string
	IsCached    int64
	IsUrgent    int64
	SourceOrder int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type NoticeAttachment struct {
	ID        string
	NoticeID  string
	Label     string
	Url       string
	LocalPath sql.NullString
	CreatedAt time.Time
}

type OfferedCourse struct {
	ClassID     string
	CourseCode  sql.NullString
	CourseTitle string
	Section     string
	Faculty     sql.NullString
	Department  sql.NullString
}

type UserRoutine struct {
	ClassID     string
	CourseCode  sql.NullString
	CourseTitle string
	AddedAt     time.Time
}

type UserState struct {
	NoticeID   string
	IsPinned   int64
	IsRead     int64
	PinnedAt   sql.NullTime
	LastReadAt sql.NullTime
}
