// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routine.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addToUserRoutine = `-- name: AddToUserRoutine :exec
INSERT INTO
  user_routine (class_id)
VALUES
  (?)
ON CONFLICT DO NOTHING
`

func (q *Queries) AddToUserRoutine(ctx context.Context, classID string) error {
	_, err := q.db.ExecContext(ctx, addToUserRoutine, classID)
	return err
}

const clearOfferedCourses = `-- name: ClearOfferedCourses :exec
DELETE FROM offered_courses
`

func (q *Queries) ClearOfferedCourses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearOfferedCourses)
	return err
}

const getUserRoutine = `-- name: GetUserRoutine :many
SELECT
  o.class_id, o.course_code, o.course_title, o.section, o.faculty, o.class_type, o.day, o.start_time, o.end_time, o.room, o.department
FROM
  user_routine u
  JOIN offered_courses o ON u.class_id = o.class_id
ORDER BY
  o.day ASC, o.start_time ASC
`

func (q *Queries) GetUserRoutine(ctx context.Context) ([]OfferedCourse, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoutine)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OfferedCourse{}
	for rows.Next() {
		var i OfferedCourse
		if err := rows.Scan(
			&i.ClassID,
			&i.CourseCode,
			&i.CourseTitle,
			&i.Section,
			&i.Faculty,
			&i.ClassType,
			&i.Day,
			&i.StartTime,
			&i.EndTime,
			&i.Room,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOfferedCourse = `-- name: InsertOfferedCourse :exec
INSERT INTO
  offered_courses (class_id, course_code, course_title, section, faculty, class_type, day, start_time, end_time, room, department)
VALUES
  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT DO NOTHING
`

type InsertOfferedCourseParams struct {
	ClassID     string
	CourseCode  sql.NullString
	CourseTitle string
	Section     string
	Faculty     sql.NullString
	ClassType   sql.NullString
	Day         sql.NullString
	StartTime   sql.NullString
	EndTime     sql.NullString
	Room        sql.NullString
	Department  sql.NullString
}

func (q *Queries) InsertOfferedCourse(ctx context.Context, arg InsertOfferedCourseParams) error {
	_, err := q.db.ExecContext(ctx, insertOfferedCourse,
		arg.ClassID,
		arg.CourseCode,
		arg.CourseTitle,
		arg.Section,
		arg.Faculty,
		arg.ClassType,
		arg.Day,
		arg.StartTime,
		arg.EndTime,
		arg.Room,
		arg.Department,
	)
	return err
}

const listOfferedCourses = `-- name: ListOfferedCourses :many
SELECT
  o.class_id, o.course_code, o.course_title, o.section, o.faculty, o.class_type, o.day, o.start_time, o.end_time, o.room, o.department
FROM
  offered_courses o
`

func (q *Queries) ListOfferedCourses(ctx context.Context) ([]OfferedCourse, error) {
	rows, err := q.db.QueryContext(ctx, listOfferedCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OfferedCourse{}
	for rows.Next() {
		var i OfferedCourse
		if err := rows.Scan(
			&i.ClassID,
			&i.CourseCode,
			&i.CourseTitle,
			&i.Section,
			&i.Faculty,
			&i.ClassType,
			&i.Day,
			&i.StartTime,
			&i.EndTime,
			&i.Room,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromUserRoutine = `-- name: RemoveFromUserRoutine :exec
DELETE FROM
  user_routine
WHERE
  class_id = ?
`

func (q *Queries) RemoveFromUserRoutine(ctx context.Context, classID string) error {
	_, err := q.db.ExecContext(ctx, removeFromUserRoutine, classID)
	return err
}
