// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routine.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addToUserRoutine = `-- name: AddToUserRoutine :exec
INSERT INTO
  user_routine (class_id)
VALUES
  (?)
ON CONFLICT(class_id) DO NOTHING
`

func (q *Queries) AddToUserRoutine(ctx context.Context, classID string) error {
	_, err := q.db.ExecContext(ctx, addToUserRoutine, classID)
	return err
}

const clearOfferedCourses = `-- name: ClearOfferedCourses :exec
DELETE FROM offered_courses
`

func (q *Queries) ClearOfferedCourses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearOfferedCourses)
	return err
}

const insertClassSchedule = `-- name: InsertClassSchedule :exec
INSERT INTO
  class_schedule (class_id, class_type, day, start_time, end_time, room)
VALUES
  (?, ?, ?, ?, ?, ?)
`

type InsertClassScheduleParams struct {
	ClassID   string
	ClassType sql.NullString
	Day       sql.NullString
	StartTime sql.NullString
	EndTime   sql.NullString
	Room      sql.NullString
}

func (q *Queries) InsertClassSchedule(ctx context.Context, arg InsertClassScheduleParams) error {
	_, err := q.db.ExecContext(ctx, insertClassSchedule,
		arg.ClassID,
		arg.ClassType,
		arg.Day,
		arg.StartTime,
		arg.EndTime,
		arg.Room,
	)
	return err
}

const insertOfferedCourse = `-- name: InsertOfferedCourse :exec
INSERT INTO
  offered_courses (class_id, course_code, course_title, section, faculty, department)
VALUES
  (?, ?, ?, ?, ?, ?)
ON CONFLICT DO NOTHING
`

type InsertOfferedCourseParams struct {
	ClassID     string
	CourseCode  sql.NullString
	CourseTitle string
	Section     string
	Faculty     sql.NullString
	Department  sql.NullString
}

func (q *Queries) InsertOfferedCourse(ctx context.Context, arg InsertOfferedCourseParams) error {
	_, err := q.db.ExecContext(ctx, insertOfferedCourse,
		arg.ClassID,
		arg.CourseCode,
		arg.CourseTitle,
		arg.Section,
		arg.Faculty,
		arg.Department,
	)
	return err
}

const listOfferedCourses = `-- name: ListOfferedCourses :many
SELECT
  o.class_id,
  o.course_code,
  o.course_title,
  o.section,
  o.faculty,
  o.department,
  s.class_type,
  s.day,
  s.start_time,
  s.end_time,
  s.room
FROM
  offered_courses o
  JOIN class_schedule s ON o.class_id = s.class_id
`

type ListOfferedCoursesRow struct {
	ClassID     string
	CourseCode  sql.NullString
	CourseTitle string
	Section     string
	Faculty     sql.NullString
	Department  sql.NullString
	ClassType   sql.NullString
	Day         sql.NullString
	StartTime   sql.NullString
	EndTime     sql.NullString
	Room        sql.NullString
}

func (q *Queries) ListOfferedCourses(ctx context.Context) ([]ListOfferedCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOfferedCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOfferedCoursesRow{}
	for rows.Next() {
		var i ListOfferedCoursesRow
		if err := rows.Scan(
			&i.ClassID,
			&i.CourseCode,
			&i.CourseTitle,
			&i.Section,
			&i.Faculty,
			&i.Department,
			&i.ClassType,
			&i.Day,
			&i.StartTime,
			&i.EndTime,
			&i.Room,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoutine = `-- name: ListUserRoutine :many
SELECT
  o.class_id,
  o.course_code,
  o.course_title,
  o.section,
  o.faculty,
  o.department,
  s.class_type,
  s.day,
  s.start_time,
  s.end_time,
  s.room
FROM
  user_routine u
  JOIN offered_courses o ON u.class_id = o.class_id
  JOIN class_schedule s ON o.class_id = s.class_id
ORDER BY
  CASE s.day
    WHEN 'Sunday' THEN 1
    WHEN 'Monday' THEN 2
    WHEN 'Tuesday' THEN 3
    WHEN 'Wednesday' THEN 4
    WHEN 'Thursday' THEN 5
    WHEN 'Friday' THEN 6
    WHEN 'Saturday' THEN 7
    ELSE 8
  END,
  s.start_time ASC
`

type ListUserRoutineRow struct {
	ClassID     string
	CourseCode  sql.NullString
	CourseTitle string
	Section     string
	Faculty     sql.NullString
	Department  sql.NullString
	ClassType   sql.NullString
	Day         sql.NullString
	StartTime   sql.NullString
	EndTime     sql.NullString
	Room        sql.NullString
}

func (q *Queries) ListUserRoutine(ctx context.Context) ([]ListUserRoutineRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoutine)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRoutineRow{}
	for rows.Next() {
		var i ListUserRoutineRow
		if err := rows.Scan(
			&i.ClassID,
			&i.CourseCode,
			&i.CourseTitle,
			&i.Section,
			&i.Faculty,
			&i.Department,
			&i.ClassType,
			&i.Day,
			&i.StartTime,
			&i.EndTime,
			&i.Room,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromUserRoutine = `-- name: RemoveFromUserRoutine :exec
DELETE FROM
  user_routine
WHERE
  class_id = ?
`

func (q *Queries) RemoveFromUserRoutine(ctx context.Context, classID string) error {
	_, err := q.db.ExecContext(ctx, removeFromUserRoutine, classID)
	return err
}
