name: Release

on:
  push:
    tags:
      - "v*" # Trigger on any version tag, e.g., v0.1.0
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    name: Build & Package App
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [windows, darwin, linux]
        arch: [amd64, arm64]
        include:
          - os: windows
            platform: windows-latest
          - os: darwin
            platform: macos-latest
          - os: linux
            platform: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # fetch all history for automated release notes

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.26.0
          cache: true

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install NSIS on Windows
        if: matrix.os == 'windows'
        uses: negrutiu/nsis-install@v3

      - name: Install Linux Dependencies
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev libwebkitgtk-6.0-dev build-essential

      - name: Install Wails3 CLI
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Build & Package Installer
        if: matrix.os != 'linux'
        run: wails3 package GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }}

      - name: Build & Package Installer
        if: matrix.os == 'linux'
        run: wails3 package

      - name: Create DMG for macOS
        if: matrix.os == 'darwin'
        run: |
          hdiutil create -volname "${{ github.event.repository.name }}" \
            -srcfolder "bin/${{ github.event.repository.name }}.app" \
            -ov -format UDZO "bin/${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}.dmg"

      - name: Rename macOS Artifacts
        if: matrix.os == 'darwin'
        run: |
          ditto -c -k --sequesterRsrc --keepParent \
            "bin/${{ github.event.repository.name }}.app" \
            "bin/${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}.zip"

          rm -rf "bin/${{ github.event.repository.name }}.app"

      - name: Rename Windows Artifacts
        if: matrix.os == 'windows'
        shell: pwsh
        run: |
          $name = "${{ github.event.repository.name }}"
          $os = "${{ matrix.os }}"
          $arch = "${{ matrix.arch }}"

          Rename-Item "bin/$name-$arch-installer.exe" "$name-$os-$arch-installer.exe"
          Rename-Item "bin/$name.exe" "$name-$os-$arch.exe"

      - name: Rename Linux Artifacts
        if: matrix.os == 'linux'
        run: |
          for file in bin/*; do
            filename=$(basename -- "$file")

            if [[ "$filename" == *.pkg.tar.zst ]]; then
              ext="pkg.tar.zst"
            elif [[ "$filename" == *.* ]]; then
              ext="${filename##*.}"
            else
              ext=""
            fi

            [[ -n "$ext" ]] && ext=".$ext"

            mv "$file" "bin/${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}${ext}"
          done

      - name: Upload Workflow Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: bin/*.*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Download Workflow Artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Generate Release Notes
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: .cliff.toml
          args: --latest
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Create Github Release
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ steps.git-cliff.outputs.content }}
          files: artifacts/**/*
          draft: false
          prerelease: false
